const NODES = [
  { x: 26, y: 14, label: "my-app/", delay: 0.1 },
  { x: 56, y: 44, label: "app/", delay: 0.5 },
  { x: 76, y: 62, label: "layout.tsx", delay: 0.7, dim: true },
  { x: 76, y: 78, label: "page.tsx", delay: 0.9, dim: true },
  { x: 56, y: 134, label: "theme/", delay: 1.3 },
  { x: 76, y: 152, label: "theme.ts", delay: 1.5, dim: true },
  { x: 56, y: 174, label: "components/", delay: 1.7 },
];

export default function ScaffoldDiagram() {
  return (
    <div className="w-full max-w-[420px]">
      <svg
        viewBox="0 0 260 200"
        className="h-auto w-full"
        role="img"
        aria-label="File tree generated by create-next-mui: app, theme, and components directories"
      >
        <line
          x1="20"
          y1="10"
          x2="20"
          y2="180"
          className="scaffold-line"
          style={{ animationDelay: "0.1s" }}
        />
        <line
          x1="20"
          y1="44"
          x2="46"
          y2="44"
          className="scaffold-line"
          style={{ animationDelay: "0.5s" }}
        />
        <line
          x1="46"
          y1="44"
          x2="46"
          y2="78"
          className="scaffold-line scaffold-line--short"
          style={{ animationDelay: "0.6s" }}
        />
        <line
          x1="46"
          y1="62"
          x2="70"
          y2="62"
          className="scaffold-line scaffold-line--short"
          style={{ animationDelay: "0.7s" }}
        />
        <line
          x1="46"
          y1="78"
          x2="70"
          y2="78"
          className="scaffold-line scaffold-line--short"
          style={{ animationDelay: "0.9s" }}
        />
        <line
          x1="20"
          y1="134"
          x2="46"
          y2="134"
          className="scaffold-line"
          style={{ animationDelay: "1.3s" }}
        />
        <line
          x1="46"
          y1="134"
          x2="46"
          y2="152"
          className="scaffold-line scaffold-line--short"
          style={{ animationDelay: "1.4s" }}
        />
        <line
          x1="46"
          y1="152"
          x2="70"
          y2="152"
          className="scaffold-line scaffold-line--short"
          style={{ animationDelay: "1.5s" }}
        />
        <line
          x1="20"
          y1="174"
          x2="46"
          y2="174"
          className="scaffold-line"
          style={{ animationDelay: "1.7s" }}
        />

        {NODES.map((n) => (
          <g
            key={n.label}
            className="scaffold-node"
            style={{ animationDelay: `${n.delay + 0.15}s` }}
          >
            <circle
              cx={n.x - 4}
              cy={n.y - 3}
              r="2"
              fill={n.dim ? "#2971b0" : "#986420"}
            />
            <text
              x={n.x}
              y={n.y}
              fontFamily="var(--font-mono, monospace)"
              fontSize="9.5"
              fill={n.dim ? "#1c7fe2" : "#3948bc"}
            >
              {n.label}
            </text>
          </g>
        ))}
      </svg>

      <style>{`
        .scaffold-line {
          stroke: #345d83;
          stroke-width: 1;
          stroke-dasharray: 220;
          stroke-dashoffset: 220;
          animation: draw 0.6s ease-out forwards;
        }
        .scaffold-line--short {
          stroke-dasharray: 60;
          stroke-dashoffset: 60;
        }
        .scaffold-node {
          opacity: 0;
          animation: fade-in 0.4s ease-out forwards;
        }
        @keyframes draw {
          to { stroke-dashoffset: 0; }
        }
        @keyframes fade-in {
          to { opacity: 1; }
        }
        @media (prefers-reduced-motion: reduce) {
          .scaffold-line, .scaffold-node {
            animation: none;
            stroke-dashoffset: 0;
            opacity: 1;
          }
        }
      `}</style>
    </div>
  );
}
