name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      # Runs both TS and JS builds concurrently in separate runners
      matrix:
        template-dir: [next-mui-template-ts, next-mui-template-js]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          # Automatically caches npm dependencies to make subsequent runs blazing fast
          cache: "npm"
          cache-dependency-path: "./${{ matrix.template-dir }}/package.json"

      - name: Install Template Dependencies
        run: |
          cd ${{ matrix.template-dir }}
          npm install

      - name: Check Eslint
        run: |
          cd ${{ matrix.template-dir }}
          npm run lint

      - name: Run Next.js Production Build
        run: |
          cd ${{ matrix.template-dir }}
          npm run build

  run-default-cli:
    name: Run default CLI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install CLI dependencies
        run: npm install

      - name: Generate project
        run: npx create-next-mui@latest my-app --yes

      - name: Verify project was created
        run: test -f my-app/package.json
