name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        template-dir:
          - next-mui-templates/base-ts
          - next-mui-templates/base-js

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: "${{ matrix.template-dir }}/package-lock.json"

      - name: Install Template Dependencies
        working-directory: ${{ matrix.template-dir }}
        run: npm install

      - name: Check ESLint
        working-directory: ${{ matrix.template-dir }}
        run: npm run lint

      - name: Run Next.js Production Build
        working-directory: ${{ matrix.template-dir }}
        run: npm run build

  run-default-cli:
    name: Run default CLI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install CLI dependencies
        run: npm install

      - name: Generate project
        run: npx create-next-mui@latest my-app --yes

      - name: Verify project was created
        run: test -f my-app/package.json
